# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('birth_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Country')),
            ],
        ),
    ]
